---
- name: Include vars.
  include_vars:
    file: defaults/main.yml
    name: main

    #- include: ../../../../../common_tasks/users.yml 

#-------------
# LVM + mount
#-------------
- name: create new partitions
  parted:
    device: /dev/disk/azure/scsi1/lun0
    number: 1
    state: present

- name: create new prim. partition lun1
  parted:
    device: /dev/disk/azure/scsi1/lun1
    number: 1
    state: present

- name:
  parted:
    device: /dev/disk/azure/scsi1/lun2
    number: 1
    state: present

- name:
  parted:
    device: /dev/disk/azure/scsi1/lun3
    number: 1
    state: present

- name:
  parted:
    device: /dev/disk/azure/scsi1/lun4
    number: 1
    state: present

- name:
  parted:
    device: /dev/disk/azure/scsi1/lun5
    number: 1
    state: present

- name:
  parted:
    device: /dev/disk/azure/scsi1/lun6
    number: 1
    state: present

- name:
  parted:
    device: /dev/disk/azure/scsi1/lun7
    number: 1
    state: present

- name:
  parted:
    device: /dev/disk/azure/scsi1/lun8
    number: 1
    state: present

- name:
  parted:
    device: /dev/disk/azure/scsi1/lun9
    number: 1
    state: present

- name: Create a volume group on top of lun0 with physical extent size 4MB
  lvg:
    vg: vg_data
    pvs: 
      - /dev/disk/azure/scsi1/lun0-part1
      - /dev/disk/azure/scsi1/lun1-part1
      - /dev/disk/azure/scsi1/lun2-part1
      - /dev/disk/azure/scsi1/lun3-part1
      - /dev/disk/azure/scsi1/lun4-part1
      - /dev/disk/azure/scsi1/lun5-part1
    pesize: "4"

- name: Create a volume group on top of lun0 with physical extent size 4MB
  lvg:
    vg: vg_log
    pvs: 
      - /dev/disk/azure/scsi1/lun6-part1
      - /dev/disk/azure/scsi1/lun7-part1
      - /dev/disk/azure/scsi1/lun8-part1
    pesize: "4"

- name: Create a volume group on top of lun0 with physical extent size 4MB
  lvg:
    vg: vg_shared
    pvs:
      - /dev/disk/azure/scsi1/lun9-part1
    pesize: "4"

- name: create a logical volume data
  lvol:
    vg: vg_data
    lv: lv_data
    opts: "-i6 -I 256K"
    size: 1572840M

- name: create a logical volume log
  lvol:
    vg: vg_log
    lv: lv_log
    opts: "-i3 -I 64K"
    size: 786420M

- name: create a logical volume shared
  lvol:
    vg: vg_shared
    lv: lv_shared
    #opts: "-i3 -l 4096"
    size: 1048572M

- name: create a xfs filesystem on lv_shared
  filesystem:
    fstype: xfs
    dev: /dev/mapper/vg_shared-lv_shared

- name: create a xfs filesystem on lv_data
  filesystem:
    fstype: xfs
    dev: /dev/mapper/vg_data-lv_data

- name: create a xfs filesystem on lv_log
  filesystem:
    fstype: xfs
    dev: /dev/mapper/vg_log-lv_log

- name: create mountpoint directory
  file: 
    path: "/hana"
    state: directory

- name: Get UUID of the hanadb lvm filesystem
  shell: |
    blkid -s UUID -o value $(readlink -f /dev/mapper/vg_data-lv_data)
  register: uuid_data

- name: mount data
  mount:
    path: /hana/data
    src: "UUID={{ uuid_data.stdout }}"
    fstype: xfs
    state: mounted

- name: Get UUID of the log lvm filesystem
  shell: |
    blkid -s UUID -o value $(readlink -f /dev/mapper/vg_log-lv_log)
  register: uuid_log

- name: mount log
  mount:
    path: /hana/log
    src: "UUID={{ uuid_log.stdout }}"
    fstype: xfs
    state: mounted


- name: Get UUID of the shared lvm filesystem
  shell: |
    blkid -s UUID -o value $(readlink -f /dev/mapper/vg_shared-lv_shared)
  register: uuid_shared

- name: mount shared
  mount:
    path: /hana/shared
    src: "UUID={{ uuid_shared.stdout }}"
    fstype: xfs
    state: mounted




    #- name: test hash
    #  debug:
    #    msg: "{{ item.name }}"
    #  with_items: "{{ lvm_config['lvg'] }}"
    #
    #- name: test hash
    #  debug:
    #    msg: "{{ item.name }}"
    #  with_items: "{{ lvm_config['lvg'].partitions['name'] }}"
